/* CVS $Id: $ */
package de.unibonn.iai.eis.diachron.semantics; 
import org.apache.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from file:/Users/jeremy/Documents/Codebase/Repository/quality/quality-vocabulary/src/main/resources/vocabularies/dqm/dqm.ttl 
 * @author Auto-generated by schemagen on 11 Jul 2017 16:39 
 */
public class DQM {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://purl.org/eis/vocab/dqm#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final Property hasAvailabilityDimension = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasAvailabilityDimension" );
    
    public static final Property hasBasicProvenanceMetric = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasBasicProvenanceMetric" );
    
    public static final Property hasCompatibleDatatype = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasCompatibleDatatype" );
    
    public static final Property hasCompletenessDimension = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasCompletenessDimension" );
    
    public static final Property hasConcisenessDimension = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasConcisenessDimension" );
    
    public static final Property hasConsistencyDimension = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasConsistencyDimension" );
    
    public static final Property hasCorrectLanguageTag = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasCorrectLanguageTag" );
    
    public static final Property hasCorrectURIUsage = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasCorrectURIUsage" );
    
    public static final Property hasCurrencyOfDatasetMetric = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasCurrencyOfDatasetMetric" );
    
    public static final Property hasDataCubePopulationCompletenessDimension = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasDataCubePopulationCompletenessDimension" );
    
    public static final Property hasDereferenceabilityBackLinksMetric = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasDereferenceabilityBackLinksMetric" );
    
    public static final Property hasDereferenceabilityForwardLinksMetric = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasDereferenceabilityForwardLinksMetric" );
    
    public static final Property hasDereferenceabilityMetric = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasDereferenceabilityMetric" );
    
    public static final Property hasDifferentSerialisationsMetric = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasDifferentSerialisationsMetric" );
    
    public static final Property hasDigitalSignatureUsage = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasDigitalSignatureUsage" );
    
    public static final Property hasEndPointAvailabilityMetric = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasEndPointAvailabilityMetric" );
    
    public static final Property hasEntitiesAsMembersOfDisjointClassesMetric = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasEntitiesAsMembersOfDisjointClassesMetric" );
    
    public static final Property hasExtendedProvenanceMetric = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasExtendedProvenanceMetric" );
    
    public static final Property hasExtensionalConcisenessMetric = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasExtensionalConcisenessMetric" );
    
    public static final Property hasFreshnessOfDatasetMetric = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasFreshnessOfDatasetMetric" );
    
    public static final Property hasHighThroughputMetric = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasHighThroughputMetric" );
    
    public static final Property hasHumanReadableLabellingMetric = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasHumanReadableLabellingMetric" );
    
    public static final Property hasHumanReadableLicenseMetric = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasHumanReadableLicenseMetric" );
    
    public static final Property hasInterlinkDetectionMetricMetric = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasInterlinkDetectionMetricMetric" );
    
    public static final Property hasInterlinkDimension = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasInterlinkDimension" );
    
    public static final Property hasInteroperabilityDimension = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasInteroperabilityDimension" );
    
    public static final Property hasInterpretabilityDimension = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasInterpretabilityDimension" );
    
    public static final Property hasLicensingDimension = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasLicensingDimension" );
    
    public static final Property hasLinkToExternalDataProvidersMetric = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasLinkToExternalDataProvidersMetric" );
    
    public static final Property hasLowLatencyMetric = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasLowLatencyMetric" );
    
    public static final Property hasMachineReadableLicenseMetric = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasMachineReadableLicenseMetric" );
    
    public static final Property hasMisplacedClassesOrPropertiesMetric = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasMisplacedClassesOrPropertiesMetric" );
    
    public static final Property hasMisreportedContentTypesMetric = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasMisreportedContentTypesMetric" );
    
    public static final Property hasMisusedOwlDatatypeOrObjectPropertiesMetric = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasMisusedOwlDatatypeOrObjectPropertiesMetric" );
    
    public static final Property hasMultipleLanguageUsageMetric = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasMultipleLanguageUsageMetric" );
    
    public static final Property hasNoBlankNodeMetric = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasNoBlankNodeMetric" );
    
    public static final Property hasNoProlixRDFMetric = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasNoProlixRDFMetric" );
    
    public static final Property hasOntologyHijackingMetric = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasOntologyHijackingMetric" );
    
    public static final Property hasPerformanceDimension = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasPerformanceDimension" );
    
    public static final Property hasPresenceOfURIRegEx = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasPresenceOfURIRegEx" );
    
    public static final Property hasProvenanceDimension = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasProvenanceDimension" );
    
    public static final Property hasRDFAvailabilityMetric = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasRDFAvailabilityMetric" );
    
    public static final Property hasRepresentationalConcisenessDimension = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasRepresentationalConcisenessDimension" );
    
    public static final Property hasReuseExistingTermsMetric = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasReuseExistingTermsMetric" );
    
    public static final Property hasReuseExistingVocabularyMetric = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasReuseExistingVocabularyMetric" );
    
    public static final Property hasScalabilityOfDataSourceMetric = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasScalabilityOfDataSourceMetric" );
    
    public static final Property hasSecurityDimension = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasSecurityDimension" );
    
    public static final Property hasShortURIsMetric = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasShortURIsMetric" );
    
    public static final Property hasSyntacticValidityDimension = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasSyntacticValidityDimension" );
    
    public static final Property hasTimelinessDimension = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasTimelinessDimension" );
    
    public static final Property hasTimelinessOfResourceMetric = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasTimelinessOfResourceMetric" );
    
    public static final Property hasUndefinedClassesAndPropertiesMetric = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasUndefinedClassesAndPropertiesMetric" );
    
    public static final Property hasUnderstandabilityDimension = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasUnderstandabilityDimension" );
    
    public static final Property hasUntypedLiteral = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasUntypedLiteral" );
    
    public static final Property hasUsageOfDeprecatedClassesOrProperties = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasUsageOfDeprecatedClassesOrProperties" );
    
    public static final Property hasUsageOfIncorrectDomainOrRangeDatatypesMetric = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasUsageOfIncorrectDomainOrRangeDatatypesMetric" );
    
    public static final Property hasValidIFPUsageMetric = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasValidIFPUsageMetric" );
    
    public static final Property hasVersatilityDimension = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasVersatilityDimension" );
    
    public static final Property hasVocabularyUsageIndication = m_model.createProperty( "http://purl.org/eis/vocab/dqm#hasVocabularyUsageIndication" );
    
    /** <p>Encompasses dimensions related to the ability to access to and retrieve the 
     *  dataset required for a particular use case</p>
     */
    public static final Resource Accessibility = m_model.createResource( "http://purl.org/eis/vocab/dqm#Accessibility" );
    
    /** <p>Metrics in this dimension measure the extent to which information (or some 
     *  portion of it) is present, obtainable and ready for use</p>
     */
    public static final Resource Availability = m_model.createResource( "http://purl.org/eis/vocab/dqm#Availability" );
    
    /** <p>Measures the degree of the basic provenance information, i.e. the creator 
     *  or publisher, of a datasource</p>
     */
    public static final Resource BasicProvenanceMetric = m_model.createResource( "http://purl.org/eis/vocab/dqm#BasicProvenanceMetric" );
    
    /** <p>** TODO **</p> */
    public static final Resource CompatibleDatatype = m_model.createResource( "http://purl.org/eis/vocab/dqm#CompatibleDatatype" );
    
    /** <p>Refers to the level the data or schema used is complete</p> */
    public static final Resource Completeness = m_model.createResource( "http://purl.org/eis/vocab/dqm#Completeness" );
    
    /** <p>Refers to the redundancy of entities, be it at the schema or the data level</p> */
    public static final Resource Conciseness = m_model.createResource( "http://purl.org/eis/vocab/dqm#Conciseness" );
    
    /** <p>Consistency means that a knowledge base is free of (logical/formal) contradictions 
     *  with respect to particular knowledge representation and inference mechanisms</p>
     */
    public static final Resource Consistency = m_model.createResource( "http://purl.org/eis/vocab/dqm#Consistency" );
    
    /** <p>Comprises dimensions that highly depend on the context of the task to be performed</p> */
    public static final Resource Contextual = m_model.createResource( "http://purl.org/eis/vocab/dqm#Contextual" );
    
    /** <p>** TODO **</p> */
    public static final Resource CorrectLanguageTag = m_model.createResource( "http://purl.org/eis/vocab/dqm#CorrectLanguageTag" );
    
    /** <p>Determines whether URIs in a dataset are represented as Slash URIs if dataset 
     *  is large, or Hash URIs otherwise</p>
     */
    public static final Resource CorrectURIUsage = m_model.createResource( "http://purl.org/eis/vocab/dqm#CorrectURIUsage" );
    
    /** <p>Assesses the freshness (currency) of the data, i.e. how fresh is the data 
     *  when delivered to the user (or how old is the data).</p>
     */
    public static final Resource CurrencyOfDatasetMetric = m_model.createResource( "http://purl.org/eis/vocab/dqm#CurrencyOfDatasetMetric" );
    
    /** <p>This metric checks if a dataset has observations that cover a gold standard 
     *  codelist.</p>
     */
    public static final Resource DataCubePopulationCompleteness = m_model.createResource( "http://purl.org/eis/vocab/dqm#DataCubePopulationCompleteness" );
    
    /** <p>Detects all local in-links or back-links (locally available triples with the 
     *  resource URI appearing as object, in the dereferenced document returned for 
     *  the resource)</p>
     */
    public static final Resource DereferenceabilityBackLinksMetric = m_model.createResource( "http://purl.org/eis/vocab/dqm#DereferenceabilityBackLinksMetric" );
    
    /** <p>Detects all forward links (locally known triples where the local URI is mentioned 
     *  in the subject)</p>
     */
    public static final Resource DereferenceabilityForwardLinksMetric = m_model.createResource( "http://purl.org/eis/vocab/dqm#DereferenceabilityForwardLinksMetric" );
    
    /** <p>Determines whether requesting a resource, identified by a URI, results in 
     *  an error code being returned (e.g. 4xx: client error or 5xx: server error), 
     *  or in a broken link</p>
     */
    public static final Resource DereferenceabilityMetric = m_model.createResource( "http://purl.org/eis/vocab/dqm#DereferenceabilityMetric" );
    
    /** <p>Detects if a dataset has more than one serialisation format</p> */
    public static final Resource DifferentSerialisationsMetric = m_model.createResource( "http://purl.org/eis/vocab/dqm#DifferentSerialisationsMetric" );
    
    /** <p>This metric checks foaf documents have a digital signature with them.</p> */
    public static final Resource DigitalSignatureUsage = m_model.createResource( "http://purl.org/eis/vocab/dqm#DigitalSignatureUsage" );
    
    /** <p>Checks whether the server (endpoint) is reachable and responds to a SPARQL 
     *  query</p>
     */
    public static final Resource EndPointAvailabilityMetric = m_model.createResource( "http://purl.org/eis/vocab/dqm#EndPointAvailabilityMetric" );
    
    /** <p>The ratio of entities described as members of disjoint classes (here: classes 
     *  explicitly known as disjoint) to the total number of entities described in 
     *  the dataset</p>
     */
    public static final Resource EntitiesAsMembersOfDisjointClassesMetric = m_model.createResource( "http://purl.org/eis/vocab/dqm#EntitiesAsMembersOfDisjointClassesMetric" );
    
    /** <p>Measures the degree of the available provenance information (Agent and Datasource 
     *  for Entities and Activities) that is available in a dataset for a consumer 
     *  to get to know the origin of the datasource using the standard W3C Prov-O</p>
     */
    public static final Resource ExtendedProvenanceMetric = m_model.createResource( "http://purl.org/eis/vocab/dqm#ExtendedProvenanceMetric" );
    
    /** <p>Provides a measure of the redundancy of the dataset at the data level, computed 
     *  as the ratio of the Number of Unique Subjects to the Total Number of Subjects</p>
     */
    public static final Resource ExtensionalConcisenessMetric = m_model.createResource( "http://purl.org/eis/vocab/dqm#ExtensionalConcisenessMetric" );
    
    /** <p>Checks if the data in the dataset is being updated with the original data</p> */
    public static final Resource FreshnessOfDatasetMetric = m_model.createResource( "http://purl.org/eis/vocab/dqm#FreshnessOfDatasetMetric" );
    
    /** <p>Measures the number of answered HTTP requests responsed by the source of the 
     *  dataset, per second</p>
     */
    public static final Resource HighThroughputMetric = m_model.createResource( "http://purl.org/eis/vocab/dqm#HighThroughputMetric" );
    
    /** <p>Assesses the percentage of entities having an rdfs:label or rdfs:comment</p> */
    public static final Resource HumanReadableLabellingMetric = m_model.createResource( "http://purl.org/eis/vocab/dqm#HumanReadableLabellingMetric" );
    
    /** <p>Verifies whether a human-readable text, stating the licensing model attributed 
     *  to the resource, has been provided as part of the dataset</p>
     */
    public static final Resource HumanReadableLicenseMetric = m_model.createResource( "http://purl.org/eis/vocab/dqm#HumanReadableLicenseMetric" );
    
    /** <p>This is a complex metric that detects good quality interlinks by measuring 
     *  the (i) interlink degree; (ii) clustering coefficient; (iii) centrality; (iv) 
     *  open sameAs chains; (v) sameAs description richness</p>
     */
    public static final Resource InterlinkDetectionMetric = m_model.createResource( "http://purl.org/eis/vocab/dqm#InterlinkDetectionMetric" );
    
    /** <p>Refers to the degree to which entities that represent the same concept are 
     *  linked to each other, be it within or between two or more data sources.</p>
     */
    public static final Resource Interlinking = m_model.createResource( "http://purl.org/eis/vocab/dqm#Interlinking" );
    
    /** <p>Refers to the degree to which the format and structure of the information 
     *  conforms to previously returned information as well as data from other sources.</p>
     */
    public static final Resource Interoperability = m_model.createResource( "http://purl.org/eis/vocab/dqm#Interoperability" );
    
    /** <p>Refers to technical aspects of the data, that is, whether information is represented 
     *  using an appropriate notation</p>
     */
    public static final Resource Interpretability = m_model.createResource( "http://purl.org/eis/vocab/dqm#Interpretability" );
    
    /** <p>Refers to dimensions that are independent of the user's context and that measure 
     *  the correctness, succinctness and consistency of the dataset</p>
     */
    public static final Resource Intrinsic = m_model.createResource( "http://purl.org/eis/vocab/dqm#Intrinsic" );
    
    /** <p>Indicates whether consumers of the dataset are explicitly granted permissions 
     *  to use it, under defined conditions (if any)</p>
     */
    public static final Resource Licensing = m_model.createResource( "http://purl.org/eis/vocab/dqm#Licensing" );
    
    /** <p>Measures the degree to which the resource is linked to external data providers, 
     *  that is, refers to the detection of links that connect the resource to external 
     *  data provided by another data sources</p>
     */
    public static final Resource LinksToExternalDataProvidersMetric = m_model.createResource( "http://purl.org/eis/vocab/dqm#LinksToExternalDataProvidersMetric" );
    
    /** <p>Measures the delay between the submission of a request to the data source 
     *  and the reception of the respective response (or the first part of it)</p>
     */
    public static final Resource LowLatencyMetric = m_model.createResource( "http://purl.org/eis/vocab/dqm#LowLatencyMetric" );
    
    /** <p>Verifies that the resource is annotated with a machine-readable indication 
     *  of the license (e.g. a VoID description or dcterms:license property)</p>
     */
    public static final Resource MachineReadableLicenseMetric = m_model.createResource( "http://purl.org/eis/vocab/dqm#MachineReadableLicenseMetric" );
    
    /** <p>Find resources that are - defined as a property but also appear on subject 
     *  or object positions in other triples (except cases like ex:prop rdf:type rdf:Property, 
     *  ex:prop rds:subPropetyOf) - defined as a class but also appear on predicate 
     *  position in other triples. The metric is computed as a ratio of misplaced 
     *  classes and properties</p>
     */
    public static final Resource MisplacedClassesOrPropertiesMetric = m_model.createResource( "http://purl.org/eis/vocab/dqm#MisplacedClassesOrPropertiesMetric" );
    
    /** <p>Checks whether the content is suitable for consumption and if such content 
     *  should be accessed</p>
     */
    public static final Resource MisreportedContentTypesMetric = m_model.createResource( "http://purl.org/eis/vocab/dqm#MisreportedContentTypesMetric" );
    
    /** <p>Detect properties that are defined as a owl:datatypeProperty but is used as 
     *  objectProperty and properties defined as a owl:object property and used as 
     *  datatype property The metric is computed as a ratio of misused properties</p>
     */
    public static final Resource MisusedOwlDatatypeOrObjectPropertiesMetric = m_model.createResource( "http://purl.org/eis/vocab/dqm#MisusedOwlDatatypeOrObjectPropertiesMetric" );
    
    /** <p>Detects if a dataset has more than one language</p> */
    public static final Resource MultipleLanguageUsageMetric = m_model.createResource( "http://purl.org/eis/vocab/dqm#MultipleLanguageUsageMetric" );
    
    /** <p>Provides a measure for the usage of blank nodes in a dataset</p> */
    public static final Resource NoBlankNodeMetric = m_model.createResource( "http://purl.org/eis/vocab/dqm#NoBlankNodeMetric" );
    
    /** <p>Detects the use of prolix RDF features, i.e reification statements, containers 
     *  and collections</p>
     */
    public static final Resource NoProlixRDFMetric = m_model.createResource( "http://purl.org/eis/vocab/dqm#NoProlixRDFMetric" );
    
    /** <p>Detects the redefinition by third parties of external classes/properties such 
     *  that reasoning over data using those external terms is affected</p>
     */
    public static final Resource OntologyHijackingMetric = m_model.createResource( "http://purl.org/eis/vocab/dqm#OntologyHijackingMetric" );
    
    /** <p>Assesses the efficiency with which a system can bind to the dataset and get 
     *  access to the information contained into it</p>
     */
    public static final Resource Performance = m_model.createResource( "http://purl.org/eis/vocab/dqm#Performance" );
    
    /** <p>This metric checks if the dataset has a regular expression defined.</p> */
    public static final Resource PresenceOfURIRegEx = m_model.createResource( "http://purl.org/eis/vocab/dqm#PresenceOfURIRegEx" );
    
    /** <p>Refers to the dataset's representation of provenance information</p> */
    public static final Resource Provenance = m_model.createResource( "http://purl.org/eis/vocab/dqm#Provenance" );
    
    /** <p>Upon request of an RDF dump, checks whether it is provided as result</p> */
    public static final Resource RDFAvailabilityMetric = m_model.createResource( "http://purl.org/eis/vocab/dqm#RDFAvailabilityMetric" );
    
    /** <p>Groups dimensions related to the design of the data, which provide information 
     *  about how the chosen representation of the data affect its quality</p>
     */
    public static final Resource Representational = m_model.createResource( "http://purl.org/eis/vocab/dqm#Representational" );
    
    /** <p>Measures the extent to which the representation of data is compact, clear 
     *  and well formatted</p>
     */
    public static final Resource RepresentationalConciseness = m_model.createResource( "http://purl.org/eis/vocab/dqm#RepresentationalConciseness" );
    
    /** <p>Provides a qualitative measure for detecting the overlap of terms used in 
     *  a dataset with existing terms.</p>
     */
    public static final Resource ReuseExistingTermsMetric = m_model.createResource( "http://purl.org/eis/vocab/dqm#ReuseExistingTermsMetric" );
    
    /** <p>Provides a qualitative measure for detecting the overlap of vocabularies used 
     *  in a dataset.</p>
     */
    public static final Resource ReuseExistingVocabularyMetric = m_model.createResource( "http://purl.org/eis/vocab/dqm#ReuseExistingVocabularyMetric" );
    
    /** <p>Determines whether the time required to answer a set of N requests divided 
     *  by N, is not longer than the time it takes to answer a single request</p>
     */
    public static final Resource ScalabilityOfDataSourceMetric = m_model.createResource( "http://purl.org/eis/vocab/dqm#ScalabilityOfDataSourceMetric" );
    
    /** <p>Refers to the extent to which data is protected against illegal alteration 
     *  and it's authenticity can be guaranteed and to the confidentiality of the 
     *  communication between a source and its consumers</p>
     */
    public static final Resource Security = m_model.createResource( "http://purl.org/eis/vocab/dqm#Security" );
    
    /** <p>Detects the use of short URIs (and the avoidance of query parameters), which 
     *  suggests that information is compactly represented and favors readability</p>
     */
    public static final Resource ShortURIsMetric = m_model.createResource( "http://purl.org/eis/vocab/dqm#ShortURIsMetric" );
    
    /** <p>The Degree to which an RDF Document conforms to the specification of the serialisation 
     *  formation</p>
     */
    public static final Resource SyntacticValidity = m_model.createResource( "http://purl.org/eis/vocab/dqm#SyntacticValidity" );
    
    /** <p>Indicates how up-to-date the data is, relative to the specific task at hand</p> */
    public static final Resource Timeliness = m_model.createResource( "http://purl.org/eis/vocab/dqm#Timeliness" );
    
    /** <p>Assesses the difference between the last modified time of the original data 
     *  source and the last modified time of the semantic web source, thereby indicating 
     *  if the resource is outdated</p>
     */
    public static final Resource TimelinessOfResourceMetric = m_model.createResource( "http://purl.org/eis/vocab/dqm#TimelinessOfResourceMetric" );
    
    /** <p>Detects undefined classes and properties</p> */
    public static final Resource UndefinedClassesAndPropertiesMetric = m_model.createResource( "http://purl.org/eis/vocab/dqm#UndefinedClassesAndPropertiesMetric" );
    
    /** <p>Refers to the easy with which data can be comprehended without ambiguity and 
     *  used by a human data consumer</p>
     */
    public static final Resource Understandability = m_model.createResource( "http://purl.org/eis/vocab/dqm#Understandability" );
    
    /** <p>** TODO **</p> */
    public static final Resource UntypedLiteralsMetric = m_model.createResource( "http://purl.org/eis/vocab/dqm#UntypedLiteralsMetric" );
    
    /** <p>This metric checks if a dataset makes use of Deprecated Classes as resource 
     *  types (defined as owl:DeprecatedClass) or Properties (defined as owl:DeprecatedProperty) 
     *  in a resource property</p>
     */
    public static final Resource UsageOfDeprecatedClassesOrProperties = m_model.createResource( "http://purl.org/eis/vocab/dqm#UsageOfDeprecatedClassesOrProperties" );
    
    /** <p>This metric tests if a property's domain and range are of the same type as 
     *  declared in the corresponding schema</p>
     */
    public static final Resource UsageOfIncorrectDomainOrRangeDatatypesMetric = m_model.createResource( "http://purl.org/eis/vocab/dqm#UsageOfIncorrectDomainOrRangeDatatypesMetric" );
    
    /** <p>This metric checks if the Inverse Functional Properties (IFP) is used correctly, 
     *  i.e. if we have S P O and P is set to be an owl:InverseFunctionalProperty, 
     *  then S is the one and only resource connected to O. If there is a triple S1 
     *  P O, then the IFP is not used correctly and thus since S1 will be 'reasoned' 
     *  to be the same as S.</p>
     */
    public static final Resource ValidIFPUsageMetric = m_model.createResource( "http://purl.org/eis/vocab/dqm#ValidIFPUsageMetric" );
    
    /** <p>Measures the availability of the data in different representations and in 
     *  an internationalised way</p>
     */
    public static final Resource Versatility = m_model.createResource( "http://purl.org/eis/vocab/dqm#Versatility" );
    
    /** <p>This metric checks the number of valid vocabularies indicated by the voID 
     *  metadata against the number of different vocabularies used.</p>
     */
    public static final Resource VocabularyUsageIndication = m_model.createResource( "http://purl.org/eis/vocab/dqm#VocabularyUsageIndication" );
    
    public static final Resource LuzzuProvenanceAgent = m_model.createResource( "http://purl.org/eis/vocab/dqm#LuzzuProvenanceAgent" );
    
}
