/* CVS $Id: $ */
package de.unibonn.iai.eis.diachron.vocabularies; 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from src/main/resources/vocabularies/dqm/dqm.trig 
 * @author Auto-generated by schemagen on 21 Mar 2014 15:06 
 */
public class DQM {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://purl.org/eis/vocab/daq#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p></p> */
    public static final Property hasAccuracyDimension = m_model.createProperty( "http://purl.org/eis/vocab/daq#hasAccuracyDimension" );
    
    /** <p></p> */
    public static final Property hasAmountOfDataDimension = m_model.createProperty( "http://purl.org/eis/vocab/daq#hasAmountOfDataDimension" );
    
    /** <p></p> */
    public static final Property hasAmountOfTriplesMetric = m_model.createProperty( "http://purl.org/eis/vocab/daq#hasAmountOfTriplesMetric" );
    
    /** <p></p> */
    public static final Property hasDeferencibilityBackLinksMetric = m_model.createProperty( "http://purl.org/eis/vocab/daq#hasDeferencibilityBackLinksMetric" );
    
    /** <p></p> */
    public static final Property hasDeferencibilityForwardLinksMetric = m_model.createProperty( "http://purl.org/eis/vocab/daq#hasDeferencibilityForwardLinksMetric" );
    
    /** <p></p> */
    public static final Property hasDereferencibilityMetric = m_model.createProperty( "http://purl.org/eis/vocab/daq#hasDereferencibilityMetric" );
    
    public static final Property hasDimension = m_model.createProperty( "http://purl.org/eis/vocab/daq#hasDimension" );
    
    /** <p></p> */
    public static final Property hasMalformedDatatypeLiteralsMetric = m_model.createProperty( "http://purl.org/eis/vocab/daq#hasMalformedDatatypeLiteralsMetric" );
    
    public static final Property hasMetric = m_model.createProperty( "http://purl.org/eis/vocab/daq#hasMetric" );
    
    /** <p></p> */
    public static final Property hasMisreportedContentTypesMetric = m_model.createProperty( "http://purl.org/eis/vocab/daq#hasMisreportedContentTypesMetric" );
    
    /** <p></p> */
    public static final Property hasUnstructuredMetric = m_model.createProperty( "http://purl.org/eis/vocab/daq#hasUnstructuredMetric" );
    
    public static final Resource Accessibility = m_model.createResource( "http://purl.org/eis/vocab/daq#Accessibility" );
    
    /** <p></p> */
    public static final Resource Accuracy = m_model.createResource( "http://purl.org/eis/vocab/daq#Accuracy" );
    
    /** <p></p> */
    public static final Resource AmountOfData = m_model.createResource( "http://purl.org/eis/vocab/daq#AmountOfData" );
    
    /** <p></p> */
    public static final Resource AmountOfTriplesMetric = m_model.createResource( "http://purl.org/eis/vocab/daq#AmountOfTriplesMetric" );
    
    /** <p></p> */
    public static final Resource Availability = m_model.createResource( "http://purl.org/eis/vocab/daq#Availability" );
    
    /** <p></p> */
    public static final Resource Contextual = m_model.createResource( "http://purl.org/eis/vocab/daq#Contextual" );
    
    /** <p></p> */
    public static final Resource DeferencibilityBackLinksMetric = m_model.createResource( "http://purl.org/eis/vocab/daq#DeferencibilityBackLinksMetric" );
    
    /** <p></p> */
    public static final Resource DeferencibilityForwardLinksMetric = m_model.createResource( "http://purl.org/eis/vocab/daq#DeferencibilityForwardLinksMetric" );
    
    /** <p></p> */
    public static final Resource DereferencibilityMetric = m_model.createResource( "http://purl.org/eis/vocab/daq#DereferencibilityMetric" );
    
    /** <p></p> */
    public static final Resource Dynamicity = m_model.createResource( "http://purl.org/eis/vocab/daq#Dynamicity" );
    
    /** <p></p> */
    public static final Resource EndPointAvailabilityMetric = m_model.createResource( "http://purl.org/eis/vocab/daq#EndPointAvailabilityMetric" );
    
    public static final Resource Intrinsic = m_model.createResource( "http://purl.org/eis/vocab/daq#Intrinsic" );
    
    /** <p></p> */
    public static final Resource MalformedDatatypeLiteralsMetric = m_model.createResource( "http://purl.org/eis/vocab/daq#MalformedDatatypeLiteralsMetric" );
    
    /** <p></p> */
    public static final Resource MisreportedContentTypesMetric = m_model.createResource( "http://purl.org/eis/vocab/daq#MisreportedContentTypesMetric" );
    
    /** <p></p> */
    public static final Resource RDFAvailabilityMetric = m_model.createResource( "http://purl.org/eis/vocab/daq#RDFAvailabilityMetric" );
    
    /** <p></p> */
    public static final Resource Representational = m_model.createResource( "http://purl.org/eis/vocab/daq#Representational" );
    
    /** <p></p> */
    public static final Resource Trust = m_model.createResource( "http://purl.org/eis/vocab/daq#Trust" );
    
    /** <p></p> */
    public static final Resource UnstructuredMetric = m_model.createResource( "http://purl.org/eis/vocab/daq#UnstructuredMetric" );
    
}
