/* CVS $Id: $ */
package de.unibonn.iai.eis.diachron.vocabularies; 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from src/main/resources/vocabularies/void/void.rdf 
 * @author Auto-generated by schemagen on 28 Feb 2014 12:27 
 */
public class VOID {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://vocab.deri.ie/void#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final Resource Oxford = m_model.createResource( "http://vocab.deri.ie/void#Department%20of%20Zoology%2C%20University%20of%20Oxford" );
    
    public static final Resource Galway = m_model.createResource( "http://vocab.deri.ie/void#Digital%20Enterprise%20Research%20Institute%2C%20NUI%20Galway" );
    
    public static final Resource LiDRC = m_model.createResource( "http://vocab.deri.ie/void#LiDRC" );
    
    public static final Resource Hausenblas = m_model.createResource( "http://vocab.deri.ie/void#Michael%20Hausenblas" );
    
    public static final Resource Talis = m_model.createResource( "http://vocab.deri.ie/void#Talis" );
    
    public static final Resource cygri = m_model.createResource( "http://vocab.deri.ie/void#cygri" );
    
    public static final Resource junzha = m_model.createResource( "http://vocab.deri.ie/void#junzha" );
    
    public static final Resource keiale = m_model.createResource( "http://vocab.deri.ie/void#keiale" );
    
    public static final Resource rdf = m_model.createResource( "http://vocab.deri.ie/void#rdf" );
    
    public static final Resource ttl = m_model.createResource( "http://vocab.deri.ie/void#ttl" );
    
}
